version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: go-finance.cayl5ldqzc4i.us-east-1.rds.amazonaws.com
      POSTGRES_USER: devmarcos
      POSTGRES_PASSWORD: karybe021313
    ports:
      - "5432:5432"
